global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pgbouncer'
    static_configs:
      - targets: ['pgbouncer_exporter:9127']    

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
  
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['embrapa-api:8000']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 15s
